language: generic
matrix:
  include:
  - &IOS_RUN
    env: ios default app english (sanity check)
    os: osx
    osx_image: xcode9.0
    before_install:
      - open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
      # skip homebrew update
      - export HOMEBREW_NO_AUTO_UPDATE=1
      #    -brew update
      - brew install libimobiledevice || echo 'ignore exit(1)'
      - brew install ideviceinstaller
      - brew install ios-deploy
      - brew install cocoapods || echo 'ignore exit(1)'
      - brew link --overwrite cocoapods

      # install pre-compiled flutter
      - FLUTTER_CHANNEL=stable
      - FLUTTER_VERSION=1.0.0-${FLUTTER_CHANNEL}
      - wget --quiet --output-document=flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_v${FLUTTER_VERSION}.zip && unzip -qq flutter.zip > /dev/null && rm flutter.zip
      - export PATH="$PATH":"$HOME/.pub-cache/bin"
      - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
      - flutter doctor -v
      - flutter devices
    script:
      - cd default_app; flutter driver lib/main.dart

  - <<: *IOS_RUN
    env: ios default app french (sanity check)
    before_script: &CHANGE_LANGUAGE_TO_FRENCH
      - xcrun simctl list
      # change language to french
      - script/ios_simulator_cli.sh "iPhone X" shutdown
      - script/ios_simulator_cli.sh "iPhone X" locale fr
      - script/ios_simulator_cli.sh "iPhone X" boot

  - <<: *IOS_RUN
    env: ios default app internationalized english
    script:
      - cd default_app_int; flutter driver lib/main.dart

  - <<: *IOS_RUN
    env: ios default app internationalized french
    before_install: *CHANGE_LANGUAGE_TO_FRENCH
    script:
      - cd default_app_int; flutter driver lib/main.dart
